GET http://localhost:8080/users

###

POST http://localhost:8080/register 

{
"id":"testId",
"email":"Joe@joe.com",
"password":"test"
}

###

POST http://localhost:8080/login

{
"email":"Joe@joe.com",
"password":"test"
}



